name: Update recently read
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          apt-get update \
          && apt-get install -yq libgconf-2-4 \
          && apt-get install -y wget --no-install-recommends \
          && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
          && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
          && apt-get update \
          && apt-get install -y google-chrome-stable --no-install-recommends \
          && rm -rf /var/lib/apt/lists/*
      - name: Update recently read
        run: yarn && npx ts-node src/index
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          BOOKLOG_USER_ID: ${{ secrets.BOOKLOG_USER_ID }} 
          TIMEZONE: Asia/Tokyo
